### ISSUE TITLE
Kolokvij

### ISSUE THREAD

**Issue by tsculac** [AnteaRokov/PAF#6]
- 1. zadatak: **12/20** ne ispisuje se odmah kod stvaranja objekta u funkciji __init__()
- 2. zadatak: **5/20** nema metoda za promjenu brzine/visine
- 3. zadatak: **5/20** u initu postavljate brzinu na 0 pa je dalje sve pogrešno
- 4. zadatak: **15/20** ideje algoritama su dobre
- 5. zadatak: **0/20**
Ukupno: **37/100**

**Comment by AnteaRokov** [comment]
Bi li mi mogli objasnit gresku u 1. I 2. Zadatku jer nisan shvatila koja je? 
Lijep pozdrav!

**Comment by AnteaRokov** [comment]
Nisu mi jasne ni ostale greške

**Comment by tsculac** [comment]
- U prvom zataku se traži "Kada se objekt stvori neka se korisniku na ekranu ispiše poruka...", objekt se stvara u ovoj liniji https://github.com/AnteaRokov/PAF/blob/master/Kolokvij/zadatak1.py#L12 i ona nema ispis već ste njega implementirali u zasebnoj funkciji
- U drugom zadatku se traži "Dodajte klasi novu metodu uz pomož koje korisnik može promijeniti pocetnu visinu i drugu uz pomoc koje korisnik moze promijeniti pocetnu brzinu". Vi u kodu nemate te metode implementirane nego imate metode koje brisu brzinu/visinu. S njima korisnik ne može promijeniti pocetnu brzinu, npr p1.set_v(20)
- U trecem zadatku ste napravili copy-paste kosog hitca kojem kao ulazni parametar kut hitca postavljate na 0 stupnjeva pa je automatski y komponenta brzine 0
- U cetvrtom zadatku su ideje algoritma dobre ali Vam ne mogu dati sve bodove kada ih nemate primjenjene s ostatkom koda na tocnom primjeru

Slobodno se javite za konzultacije ako ima dodatnih nejasnoca!

**Comment by AnteaRokov** [comment]
Kad mogu doci na konzultacije jer stvarno ne razumin neke stvari?

Dohvati Outlook za iOS<https://aka.ms/o0ukef>
________________________________
Šalje: Toni Sculac ***@***.***>
Poslano: Tuesday, April 20, 2021 2:02:11 PM
Prima: AnteaRokov/PAF ***@***.***>
Kopija: Antea Rokov ***@***.***>; Comment ***@***.***>
Predmet: Re: [AnteaRokov/PAF] Kolokvij (#6)


  *   U prvom zataku se traži "Kada se objekt stvori neka se korisniku na ekranu ispiše poruka...", objekt se stvara u ovoj liniji https://github.com/AnteaRokov/PAF/blob/master/Kolokvij/zadatak1.py#L12 i ona nema ispis već ste njega implementirali u zasebnoj funkciji
  *   U drugom zadatku se traži "Dodajte klasi novu metodu uz pomož koje korisnik može promijeniti pocetnu visinu i drugu uz pomoc koje korisnik moze promijeniti pocetnu brzinu". Vi u kodu nemate te metode implementirane nego imate metode koje brisu brzinu/visinu. S njima korisnik ne može promijeniti pocetnu brzinu, npr p1.set_v(20)
  *   U trecem zadatku ste napravili copy-paste kosog hitca kojem kao ulazni parametar kut hitca postavljate na 0 stupnjeva pa je automatski y komponenta brzine 0
  *   U cetvrtom zadatku su ideje algoritma dobre ali Vam ne mogu dati sve bodove kada ih nemate primjenjene s ostatkom koda na tocnom primjeru

Slobodno se javite za konzultacije ako ima dodatnih nejasnoca!

**Comment by tsculac** [comment]
Npr. da li Vam odgovara sutra neki termin od 12:00 do 16:00?

**Comment by AnteaRokov** [comment]
Moze u 12 odmah

Dohvati Outlook za iOS<https://aka.ms/o0ukef>
________________________________
Šalje: Toni Sculac ***@***.***>
Poslano: Tuesday, April 20, 2021 2:06:04 PM
Prima: AnteaRokov/PAF ***@***.***>
Kopija: Antea Rokov ***@***.***>; Comment ***@***.***>
Predmet: Re: [AnteaRokov/PAF] Kolokvij (#6)


Npr. da li Vam odgovara sutra neki termin od 12:00 do 16:00?

**Comment by tsculac** [comment]
Moze, vidimo se.

**Comment by AnteaRokov** [comment]
Hvala!
Pozdrav!

Dohvati Outlook za iOS<https://aka.ms/o0ukef>
________________________________
Šalje: Toni Sculac ***@***.***>
Poslano: Tuesday, April 20, 2021 2:07:28 PM
Prima: AnteaRokov/PAF ***@***.***>
Kopija: Antea Rokov ***@***.***>; Comment ***@***.***>
Predmet: Re: [AnteaRokov/PAF] Kolokvij (#6)


Moze, vidimo se.
